on: pull_request
name: Github Action for Terratest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Test SS
        run: |
          chmod +x run.sh
          ./run.sh
          ls
