on: pull_request
name: My cool Action
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.3' 
      - name: Run build
        run: go init mod test
      - name: Install dependencies
        run: |
          go version
          go get -u github.com/gruntwork-io/terratest/modules/terraform
          go get -u github.com/stretchr/testify/assert
      - name: Run testing
        run: go test -v
